version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "5174:5173"
    networks:
      - mern01
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "6009:6009"
    networks:
      - mern01

networks:
  mern01:
    driver: bridge

